import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:get/get.dart';

import 'package:google_fonts/google_fonts.dart';

Widget textDisplayLarge(
    String text,{
    double fontSize = 45,
    Color? color,
    FontStyle? fontStyle,
    FontWeight fontWeight = FontWeight.w500,
    Color? backGroundColor,
    TextDirection? textDirection,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    Color? decorationColor,
    TextStyle? textStyle,
    Paint? background,
    TextDecorationStyle? textDecorationStyle,
    double? wordSpacing,
    TextBaseline? textBaseline,
    List<Shadow>? shadow,
    Locale? locale,
    double? height,
    double? decorationThickness,
    List<FontFeature>? fontFeatures,
    Paint? foreground,
    double? letterSpacing,
    TextOverflow? overflow}) {
  return Text(
    text,
    textDirection: textDirection,
    maxLines: maxLines,
    textAlign: textAlign,
    style: textStyleCustom(
      fontSize: fontSize,
      color: color,
      decoration: decoration,
      decorationColor: decorationColor,
      textStyle: textStyle,
      background: background,
      textDecorationStyle: textDecorationStyle,
      wordSpacing: wordSpacing,
      textBaseline: textBaseline,
      shadow: shadow,
      locale: locale,
      height: height,
      decorationThickness: decorationThickness,
      fontFeatures: fontFeatures,
      foreground: foreground,
      letterSpacing: letterSpacing,
      fontWeight: fontWeight,
      backGroundColor: backGroundColor,
      fontStyle: fontStyle,
    ),
  );
}

Widget textDisplayMedium(
    String text,{
    double fontSize = 35,
    Color? color,
    FontStyle? fontStyle,
    FontWeight fontWeight = FontWeight.w500,
    Color? backGroundColor,
    TextDirection? textDirection,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    Color? decorationColor,
    TextStyle? textStyle,
    Paint? background,
    TextDecorationStyle? textDecorationStyle,
    double? wordSpacing,
    TextBaseline? textBaseline,
    List<Shadow>? shadow,
    Locale? locale,
    double? height,
    double? decorationThickness,
    List<FontFeature>? fontFeatures,
    Paint? foreground,
    double? letterSpacing,
    TextOverflow? overflow}) {
  return Text(
    text,
    textDirection: textDirection,
    maxLines: maxLines,
    textAlign: textAlign,
    style: textStyleCustom(
      fontSize: fontSize,
      color: color,
      decoration: decoration,
      decorationColor: decorationColor,
      textStyle: textStyle,
      background: background,
      textDecorationStyle: textDecorationStyle,
      wordSpacing: wordSpacing,
      textBaseline: textBaseline,
      shadow: shadow,
      locale: locale,
      height: height,
      decorationThickness: decorationThickness,
      fontFeatures: fontFeatures,
      foreground: foreground,
      letterSpacing: letterSpacing,
      fontWeight: fontWeight,
      backGroundColor: backGroundColor,
      fontStyle: fontStyle,
    ),
  );
}

Widget textDisplaySmall(
    String text,{
    double fontSize = 25,
    Color? color,
    FontStyle? fontStyle,
    FontWeight fontWeight = FontWeight.w500,
    Color? backGroundColor,
    TextDirection? textDirection,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    Color? decorationColor,
    TextStyle? textStyle,
    Paint? background,
    TextDecorationStyle? textDecorationStyle,
    double? wordSpacing,
    TextBaseline? textBaseline,
    List<Shadow>? shadow,
    Locale? locale,
    double? height,
    double? decorationThickness,
    List<FontFeature>? fontFeatures,
    Paint? foreground,
    double? letterSpacing,
    TextOverflow? overflow}) {
  return Text(
    text,
    textDirection: textDirection,
    maxLines: maxLines,
    textAlign: textAlign,
    style: textStyleCustom(
      fontSize: fontSize,
      color: color,
      decoration: decoration,
      decorationColor: decorationColor,
      textStyle: textStyle,
      background: background,
      textDecorationStyle: textDecorationStyle,
      wordSpacing: wordSpacing,
      textBaseline: textBaseline,
      shadow: shadow,
      locale: locale,
      height: height,
      decorationThickness: decorationThickness,
      fontFeatures: fontFeatures,
      foreground: foreground,
      letterSpacing: letterSpacing,
      fontWeight: fontWeight,
      backGroundColor: backGroundColor,
      fontStyle: fontStyle,
    ),
  );
}

Widget textHeadlineLarge(
    String text,{
    double fontSize = 28.5,
    Color? color,
    FontStyle? fontStyle,
    FontWeight fontWeight = FontWeight.normal,
    Color? backGroundColor,
    TextDirection? textDirection,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    Color? decorationColor,
    TextStyle? textStyle,
    Paint? background,
    TextDecorationStyle? textDecorationStyle,
    double? wordSpacing,
    TextBaseline? textBaseline,
    List<Shadow>? shadow,
    Locale? locale,
    double? height,
    double? decorationThickness,
    List<FontFeature>? fontFeatures,
    Paint? foreground,
    double? letterSpacing,
    TextOverflow? overflow}) {
  return Text(
    text,
    textDirection: textDirection,
    maxLines: maxLines,
    textAlign: textAlign,
    style: textStyleCustom(
      fontSize: fontSize,
      color: color,
      decoration: decoration,
      decorationColor: decorationColor,
      textStyle: textStyle,
      background: background,
      textDecorationStyle: textDecorationStyle,
      wordSpacing: wordSpacing,
      textBaseline: textBaseline,
      shadow: shadow,
      locale: locale,
      height: height,
      decorationThickness: decorationThickness,
      fontFeatures: fontFeatures,
      foreground: foreground,
      letterSpacing: letterSpacing,
      fontWeight: fontWeight,
      backGroundColor: backGroundColor,
      fontStyle: fontStyle,
    ),
  );
}

Widget textHeadlineMedium(
    String text,{
    double fontSize = 25.5,
    Color? color,
    FontStyle? fontStyle,
    FontWeight fontWeight = FontWeight.normal,
    Color? backGroundColor,
    TextDirection? textDirection,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    Color? decorationColor,
    TextStyle? textStyle,
    Paint? background,
    TextDecorationStyle? textDecorationStyle,
    double? wordSpacing,
    TextBaseline? textBaseline,
    List<Shadow>? shadow,
    Locale? locale,
    double? height,
    double? decorationThickness,
    List<FontFeature>? fontFeatures,
    Paint? foreground,
    double? letterSpacing,
    TextOverflow? overflow}) {
  return Text(
    text,
    textDirection: textDirection,
    maxLines: maxLines,
    textAlign: textAlign,
    style: textStyleCustom(
      fontSize: fontSize,
      color: color,
      decoration: decoration,
      decorationColor: decorationColor,
      textStyle: textStyle,
      background: background,
      textDecorationStyle: textDecorationStyle,
      wordSpacing: wordSpacing,
      textBaseline: textBaseline,
      shadow: shadow,
      locale: locale,
      height: height,
      decorationThickness: decorationThickness,
      fontFeatures: fontFeatures,
      foreground: foreground,
      letterSpacing: letterSpacing,
      fontWeight: fontWeight,
      backGroundColor: backGroundColor,
      fontStyle: fontStyle,
    ),
  );
}

Widget textHeadlineSmall(
    String text,{
    double fontSize = 20,
    Color? color,
    FontStyle? fontStyle,
    FontWeight fontWeight = FontWeight.normal,
    Color? backGroundColor,
    TextDirection? textDirection,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    Color? decorationColor,
    TextStyle? textStyle,
    Paint? background,
    TextDecorationStyle? textDecorationStyle,
    double? wordSpacing,
    TextBaseline? textBaseline,
    List<Shadow>? shadow,
    Locale? locale,
    double? height,
    double? decorationThickness,
    List<FontFeature>? fontFeatures,
    Paint? foreground,
    double? letterSpacing,
    TextOverflow? overflow}) {
  return Text(
    text,
    textDirection: textDirection,
    maxLines: maxLines,
    textAlign: textAlign,
    style: textStyleCustom(
      fontSize: fontSize,
      color: color,
      decoration: decoration,
      decorationColor: decorationColor,
      textStyle: textStyle,
      background: background,
      textDecorationStyle: textDecorationStyle,
      wordSpacing: wordSpacing,
      textBaseline: textBaseline,
      shadow: shadow,
      locale: locale,
      height: height,
      decorationThickness: decorationThickness,
      fontFeatures: fontFeatures,
      foreground: foreground,
      letterSpacing: letterSpacing,
      fontWeight: fontWeight,
      backGroundColor: backGroundColor,
      fontStyle: fontStyle,
    ),
  );
}

Widget textTitleLarge(
    String text,{
    double fontSize = 18.5,
    Color? color,
    FontStyle? fontStyle,
    FontWeight fontWeight = FontWeight.w700,
    Color? backGroundColor,
    TextDirection? textDirection,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    Color? decorationColor,
    TextStyle? textStyle,
    Paint? background,
    TextDecorationStyle? textDecorationStyle,
    double? wordSpacing,
    TextBaseline? textBaseline,
    List<Shadow>? shadow,
    Locale? locale,
    double? height,
    double? decorationThickness,
    List<FontFeature>? fontFeatures,
    Paint? foreground,
    double? letterSpacing,
    TextOverflow? overflow}) {
  return Text(
    text,
    textDirection: textDirection,
    maxLines: maxLines,
    textAlign: textAlign,
    style: textStyleCustom(
      fontSize: fontSize,
      color: color,
      decoration: decoration,
      decorationColor: decorationColor,
      textStyle: textStyle,
      background: background,
      textDecorationStyle: textDecorationStyle,
      wordSpacing: wordSpacing,
      textBaseline: textBaseline,
      shadow: shadow,
      locale: locale,
      height: height,
      decorationThickness: decorationThickness,
      fontFeatures: fontFeatures,
      foreground: foreground,
      letterSpacing: letterSpacing,
      fontWeight: fontWeight,
      backGroundColor: backGroundColor,
      fontStyle: fontStyle,
    ),
  );
}

Widget textTitleMedium(
    String text,{
    double fontSize = 16.5,
    Color? color,
    FontStyle? fontStyle,
    FontWeight fontWeight = FontWeight.w700,
    Color? backGroundColor,
    TextDirection? textDirection,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    Color? decorationColor,
    TextStyle? textStyle,
    Paint? background,
    TextDecorationStyle? textDecorationStyle,
    double? wordSpacing,
    TextBaseline? textBaseline,
    List<Shadow>? shadow,
    Locale? locale,
    double? height,
    double? decorationThickness,
    List<FontFeature>? fontFeatures,
    Paint? foreground,
    double? letterSpacing,
    TextOverflow? overflow}) {
  return Text(
    text,
    textDirection: textDirection,
    maxLines: maxLines,
    textAlign: textAlign,
    style: textStyleCustom(
      fontSize: fontSize,
      color: color,
      decoration: decoration,
      decorationColor: decorationColor,
      textStyle: textStyle,
      background: background,
      textDecorationStyle: textDecorationStyle,
      wordSpacing: wordSpacing,
      textBaseline: textBaseline,
      shadow: shadow,
      locale: locale,
      height: height,
      decorationThickness: decorationThickness,
      fontFeatures: fontFeatures,
      foreground: foreground,
      letterSpacing: letterSpacing,
      fontWeight: fontWeight,
      backGroundColor: backGroundColor,
      fontStyle: fontStyle,
    ),
  );
}

Widget textTitleSmall(
    String text,{
    double fontSize = 13.5,
    Color? color,
    FontStyle? fontStyle,
    FontWeight fontWeight = FontWeight.w700,
    Color? backGroundColor,
    TextDirection? textDirection,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    Color? decorationColor,
    TextStyle? textStyle,
    Paint? background,
    TextDecorationStyle? textDecorationStyle,
    double? wordSpacing,
    TextBaseline? textBaseline,
    List<Shadow>? shadow,
    Locale? locale,
    double? height,
    double? decorationThickness,
    List<FontFeature>? fontFeatures,
    Paint? foreground,
    double? letterSpacing,
    TextOverflow? overflow}) {
  return Text(
    text,
    textDirection: textDirection,
    maxLines: maxLines,
    textAlign: textAlign,
    style: textStyleCustom(
      fontSize: fontSize,
      color: color,
      decoration: decoration,
      decorationColor: decorationColor,
      textStyle: textStyle,
      background: background,
      textDecorationStyle: textDecorationStyle,
      wordSpacing: wordSpacing,
      textBaseline: textBaseline,
      shadow: shadow,
      locale: locale,
      height: height,
      decorationThickness: decorationThickness,
      fontFeatures: fontFeatures,
      foreground: foreground,
      letterSpacing: letterSpacing,
      fontWeight: fontWeight,
      backGroundColor: backGroundColor,
      fontStyle: fontStyle,
    ),
  );
}

Widget textLableLarge(
    String text,{
    double fontSize = 18,
    Color? color,
    FontStyle? fontStyle,
    FontWeight fontWeight = FontWeight.w600,
    Color? backGroundColor,
    TextDirection? textDirection,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    Color? decorationColor,
    TextStyle? textStyle,
    Paint? background,
    TextDecorationStyle? textDecorationStyle,
    double? wordSpacing,
    TextBaseline? textBaseline,
    List<Shadow>? shadow,
    Locale? locale,
    double? height,
    double? decorationThickness,
    List<FontFeature>? fontFeatures,
    Paint? foreground,
    double? letterSpacing,
    TextOverflow? overflow}) {
  return Text(
    text,
    textDirection: textDirection,
    maxLines: maxLines,
    textAlign: textAlign,
    style: textStyleCustom(
      fontSize: fontSize,
      color: color,
      decoration: decoration,
      decorationColor: decorationColor,
      textStyle: textStyle,
      background: background,
      textDecorationStyle: textDecorationStyle,
      wordSpacing: wordSpacing,
      textBaseline: textBaseline,
      shadow: shadow,
      locale: locale,
      height: height,
      decorationThickness: decorationThickness,
      fontFeatures: fontFeatures,
      foreground: foreground,
      letterSpacing: letterSpacing,
      fontWeight: fontWeight,
      backGroundColor: backGroundColor,
      fontStyle: fontStyle,
    ),
  );
}

Widget textLableMedium(
    String text,{
    double fontSize = 15.5,
    Color? color,
    FontStyle? fontStyle,
    FontWeight fontWeight = FontWeight.w600,
    Color? backGroundColor,
    TextDirection? textDirection,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    Color? decorationColor,
    TextStyle? textStyle,
    Paint? background,
    TextDecorationStyle? textDecorationStyle,
    double? wordSpacing,
    TextBaseline? textBaseline,
    List<Shadow>? shadow,
    Locale? locale,
    double? height,
    double? decorationThickness,
    List<FontFeature>? fontFeatures,
    Paint? foreground,
    double? letterSpacing,
    TextOverflow? overflow}) {
  return Text(
    text,
    textDirection: textDirection,
    maxLines: maxLines,
    textAlign: textAlign,
    style: textStyleCustom(
      fontSize: fontSize,
      color: color,
      decoration: decoration,
      decorationColor: decorationColor,
      textStyle: textStyle,
      background: background,
      textDecorationStyle: textDecorationStyle,
      wordSpacing: wordSpacing,
      textBaseline: textBaseline,
      shadow: shadow,
      locale: locale,
      height: height,
      decorationThickness: decorationThickness,
      fontFeatures: fontFeatures,
      foreground: foreground,
      letterSpacing: letterSpacing,
      fontWeight: fontWeight,
      backGroundColor: backGroundColor,
      fontStyle: fontStyle,
    ),
  );
}

Widget textLableSmall(
    String text,{
    double fontSize = 13,
    Color? color,
    FontStyle? fontStyle,
    FontWeight fontWeight = FontWeight.w600,
    Color? backGroundColor,
    TextDirection? textDirection,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    Color? decorationColor,
    TextStyle? textStyle,
    Paint? background,
    TextDecorationStyle? textDecorationStyle,
    double? wordSpacing,
    TextBaseline? textBaseline,
    List<Shadow>? shadow,
    Locale? locale,
    double? height,
    double? decorationThickness,
    List<FontFeature>? fontFeatures,
    Paint? foreground,
    double? letterSpacing,
    TextOverflow? overflow}) {
  return Text(
    text,
    textDirection: textDirection,
    maxLines: maxLines,
    textAlign: textAlign,
    style: textStyleCustom(
      fontSize: fontSize,
      color: color,
      decoration: decoration,
      decorationColor: decorationColor,
      textStyle: textStyle,
      background: background,
      textDecorationStyle: textDecorationStyle,
      wordSpacing: wordSpacing,
      textBaseline: textBaseline,
      shadow: shadow,
      locale: locale,
      height: height,
      decorationThickness: decorationThickness,
      fontFeatures: fontFeatures,
      foreground: foreground,
      letterSpacing: letterSpacing,
      fontWeight: fontWeight,
      backGroundColor: backGroundColor,
      fontStyle: fontStyle,
    ),
  );
}

Widget textBodyLarge(
    String text,{
    double fontSize = 18,
    Color? color,
    FontStyle? fontStyle,
    FontWeight fontWeight = FontWeight.normal,
    Color? backGroundColor,
    TextDirection? textDirection,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    Color? decorationColor,
    TextStyle? textStyle,
    Paint? background,
    TextDecorationStyle? textDecorationStyle,
    double? wordSpacing,
    TextBaseline? textBaseline,
    List<Shadow>? shadow,
    Locale? locale,
    double? height,
    double? decorationThickness,
    List<FontFeature>? fontFeatures,
    Paint? foreground,
    double? letterSpacing,
    TextOverflow? overflow}) {
  return Text(
    text,
    textDirection: textDirection,
    maxLines: maxLines,
    textAlign: textAlign,
    style: textStyleCustom(
      fontSize: fontSize,
      color: color,
      decoration: decoration,
      decorationColor: decorationColor,
      textStyle: textStyle,
      background: background,
      textDecorationStyle: textDecorationStyle,
      wordSpacing: wordSpacing,
      textBaseline: textBaseline,
      shadow: shadow,
      locale: locale,
      height: height,
      decorationThickness: decorationThickness,
      fontFeatures: fontFeatures,
      foreground: foreground,
      letterSpacing: letterSpacing,
      fontWeight: fontWeight,
      backGroundColor: backGroundColor,
      fontStyle: fontStyle,
    ),
  );
}

Widget textBodyMedium(
    String text,{
    double fontSize = 15.5,
    Color? color,
    FontStyle? fontStyle,
    FontWeight fontWeight = FontWeight.normal,
    Color? backGroundColor,
    TextDirection? textDirection,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    Color? decorationColor,
    TextStyle? textStyle,
    Paint? background,
    TextDecorationStyle? textDecorationStyle,
    double? wordSpacing,
    TextBaseline? textBaseline,
    List<Shadow>? shadow,
    Locale? locale,
    double? height,
    double? decorationThickness,
    List<FontFeature>? fontFeatures,
    Paint? foreground,
    double? letterSpacing,
    TextOverflow? overflow}) {
  return Text(
    text,
    textDirection: textDirection,
    maxLines: maxLines,
    textAlign: textAlign,
    style: textStyleCustom(
      fontSize: fontSize,
      color: color,
      decoration: decoration,
      decorationColor: decorationColor,
      textStyle: textStyle,
      background: background,
      textDecorationStyle: textDecorationStyle,
      wordSpacing: wordSpacing,
      textBaseline: textBaseline,
      shadow: shadow,
      locale: locale,
      height: height,
      decorationThickness: decorationThickness,
      fontFeatures: fontFeatures,
      foreground: foreground,
      letterSpacing: letterSpacing,
      fontWeight: fontWeight,
      backGroundColor: backGroundColor,
      fontStyle: fontStyle,
    ),
  );
}

Widget textBodySmall(
    String text,{
    double fontSize = 12.5,
    Color? color,
    FontStyle? fontStyle,
    FontWeight fontWeight = FontWeight.normal,
    Color? backGroundColor,
    TextDirection? textDirection,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    Color? decorationColor,
    TextStyle? textStyle,
    Paint? background,
    TextDecorationStyle? textDecorationStyle,
    double? wordSpacing,
    TextBaseline? textBaseline,
    List<Shadow>? shadow,
    Locale? locale,
    double? height,
    double? decorationThickness,
    List<FontFeature>? fontFeatures,
    Paint? foreground,
    double? letterSpacing,
    TextOverflow? overflow}) {
  return Text(
    text,
    textDirection: textDirection,
    maxLines: maxLines,
    textAlign: textAlign,
    overflow: overflow,
    style: textStyleCustom(
      fontSize: fontSize,
      color: color,
      decoration: decoration,
      decorationColor: decorationColor,
      textStyle: textStyle,
      background: background,
      textDecorationStyle: textDecorationStyle,
      wordSpacing: wordSpacing,
      textBaseline: textBaseline,
      shadow: shadow,
      locale: locale,
      height: height,
      decorationThickness: decorationThickness,
      fontFeatures: fontFeatures,
      foreground: foreground,
      letterSpacing: letterSpacing,
      fontWeight: fontWeight,
      backGroundColor: backGroundColor,
      fontStyle: fontStyle,
    ),
  );
}

TextStyle textStyleCustom(
    {required double fontSize,
    Color? color,
    FontStyle? fontStyle,
    FontWeight? fontWeight,
    Color? backGroundColor,
    TextDecoration? decoration,
    Color? decorationColor,
    TextStyle? textStyle,
    Paint? background,
    TextDecorationStyle? textDecorationStyle,
    double? wordSpacing,
    TextBaseline? textBaseline,
    List<Shadow>? shadow,
    Locale? locale,
    double? height,
    double? decorationThickness,
    List<FontFeature>? fontFeatures,
    Paint? foreground,
    double? letterSpacing}) {
  return GoogleFonts.beVietnamPro(
    fontSize: fontSize,
    color: color ?? Get.theme.colorScheme.onBackground,
    decoration: decoration,
    decorationColor: decorationColor,
    textStyle: textStyle,
    background: background,
    decorationStyle: textDecorationStyle,
    wordSpacing: wordSpacing,
    textBaseline: textBaseline,
    shadows: shadow,
    locale: locale,
    height: height,
    decorationThickness: decorationThickness,
    fontFeatures: fontFeatures,
    foreground: foreground,
    letterSpacing: letterSpacing,
    fontWeight: fontWeight,
    backgroundColor: backGroundColor,
    fontStyle: fontStyle,
  );
}
